{% set name = "pytest-xdist" %}
{% set version = "1.18.0" %}
{% set hash_type = "sha256" %}
{% set hash = "97d2237b3acd11195c54a80af9ca2e951ef356363e052938fec1e83b67015fa3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - execnet >=1.1
    - py >=1.4.22
    - pytest >=3.0.0
    - setuptools
    - setuptools_scm
  run:
    - python
    - execnet >=1.1
    - py >=1.4.22
    - pytest >=3.0.0
    - setuptools

test:
  imports:
    - xdist

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  dev_url: https://github.com/pytest-dev/pytest-xdist

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
