{% set name = "pytest-xdist" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_xdist-{{ version }}.tar.gz
  sha256: 7e578125ec9bc6050861aa93f2d59f1d8d085595d6551c2c90b6f4fad8d3a9f1

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0
    - setuptools-scm >=6.2.3
  run:
    - python
    - execnet >=2.1
    - pytest >=7.0.0
  run_constrained:
    - psutil >=3.0

test:
  source_files:
    - testing
  imports:
    - xdist
  files:
    - dummy_test.py
  commands:
    - pytest -n2 dummy_test.py
    - pytest -vv testing -k "not test_ignore_sys_path_hook_entry"  # [win]
    - pytest -vv testing -k "not test_internal_errors_propagate_to_controller"  # [s390x]
    - pytest -vv testing -k "not (test_keyboardinterrupt_hooks_issue79 or test_simple)"  # [osx]
    - pytest -vv testing  # [not (osx or s390x or win)]
    - pip check
  requires:
    - pip
    - filelock

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  description: |
    The pytest-xdist plugin extends pytest with new test execution modes, the most used being
    distributing tests across multiple CPUs to speed up test execution
  dev_url: https://github.com/pytest-dev/pytest-xdist
  doc_url: https://pytest-xdist.readthedocs.io

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
