{% set version = "3.6.1" %}

package:
  name: pytest-xdist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-xdist/pytest-xdist-{{ version }}.tar.gz
  sha256: ead156a4db231eec769737f57668ef58a2084a34b2e55c4a8fa20d861107300d

build:
  number: 0
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - wheel
    - setuptools-scm >=6.2.3
  run:
    - python
    - execnet >=2.1
    - pytest >=7.0.0
  run_constrained:
    - psutil >=3.0

test:
  source_files:
    - testing
  imports:
    - xdist
  files:
    - dummy_test.py
  commands:
    - pytest -n2 dummy_test.py
    - pytest -vv testing -k "not test_internal_errors_propagate_to_controller"  # [s390x]
    - pytest -vv testing -k "not (test_keyboardinterrupt_hooks_issue79 or test_simple)"  # [osx]
    - pytest -vv testing   # [not (osx or s390x)]
    - pip check
  requires:
    - pip
    - filelock

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  description: |
    The pytest-xdist plugin extends pytest with new test execution modes, the most used being 
    distributing tests across multiple CPUs to speed up test execution
  dev_url: https://github.com/pytest-dev/pytest-xdist
  doc_url: https://pytest-xdist.readthedocs.io

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
