{% set name = "pytest-xdist" %}
{% set version = "1.19.0" %}
{% set hash_type = "sha256" %}
{% set hash = "c066d27f884cc6c8d1d384176ace6494376d4a6cc1602b79489e6761879acd2a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - execnet >=1.1
    - py >=1.4.22
    - pytest >=3.0.0
    - setuptools
    - setuptools_scm
  run:
    - python
    - execnet >=1.1
    - py >=1.4.22
    - pytest >=3.0.0
    - setuptools
    - pytest-forked

test:
  imports:
    - xdist
  files:
    - dummy_test.py
  commands:
    - pytest -n2 dummy_test.py

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  dev_url: https://github.com/pytest-dev/pytest-xdist

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
