{% set name = "pytest-xdist" %}
{% set version = "1.22.1" %}
{% set hash_type = "sha256" %}
{% set hash = "fcd6f36bab93b0b24ec45ca12f798b9b3af71da826db0b0794b358d2f5c038de" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools_scm
  run:
    - python
    - execnet >=1.1
    - pytest >=3.0.0
    - pytest-forked

test:
  imports:
    - xdist
  files:
    - dummy_test.py
  commands:
    - pytest -n2 dummy_test.py

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  dev_url: https://github.com/pytest-dev/pytest-xdist

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
