{% set version = "1.16.0" %}
{% set hash_type = "sha256" %}
{% set hash = "42e5a1e5da9d7cff3e74b07f8692598382f95624f234ff7e00a3b1237e0feba2" %}

package:
  name: pytest-xdist
  version: {{ version }}

source:
  fn: pytest-xdist-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-xdist/pytest-xdist-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - execnet >=1.1
    - py >=1.4.22
    - pytest >=2.4.2
    - setuptools
    - setuptools_scm
  run:
    - python
    - execnet >=1.1
    - py >=1.4.22
    - pytest >=2.4.2
    - setuptools

test:
  imports:
    - xdist

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  dev_url: https://github.com/pytest-dev/pytest-xdist

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
