{% set version = "1.33.0" %}

package:
  name: pytest-xdist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-xdist/pytest-xdist-{{ version }}.tar.gz
  sha256: 833b902b16473162cc0572d5bd7b63f8b843df63a4ada9c8af1270d31db17607

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - execnet >=1.1
    - pytest >=4.4.0
    - pytest-forked
    - six

test:
  imports:
    - xdist
  files:
    - dummy_test.py
  commands:
    - pytest -n2 dummy_test.py

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  dev_url: https://github.com/pytest-dev/pytest-xdist

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
