travis:
  secure:
    BINSTAR_TOKEN: J/j573RBRhXe/KkY6FdQnmvDeJTsUbMgYwlhYPTcNEhabDla5lt2azpJSEdH484y8m4aejGlnyYGqX9Dot8WP9kgCdbdk4710dqUPtD29n867DPCjB5OJPHc9uiWanWXF9heJcvqoQc1Z7IzqQgvvBBrnuNutKwTgP000xlcU/C3wZWmN93XgfLFbSKQDaYKOCg2RfTcLKqSAn5LmITDhF4AMRsK37fkk5clwV0zqLvN8KckduZ5aUFLjckcfD5ZG3AGWhse2QbkPMDK3ZifgEPEHNZJN41w8UPECDutY/QRzialZZMKA7XrjEbUnFrgR9Nky4A+1E2X9yBcjcOMYKa26ZzHdhLX81MrfsUFEuYXiItt8Km6zA7pCQIbwy4or2Ocs83bvMDajzu1ciDiP8Y9rFIcMVPdZTGZQEF8o1oekxHGBuhIRD4pZZ78F+yoN1fx0A+knc+EzKD/75ZE1VSQ5fGWDSSKT3iDe4CT+cVGWT/Gfxanbu21gKJxGvOc0olWK1IqjjhmYzgjWxkME6tmvYCGYd9hgQjKKoqkvre8u/Ocy4+0sMUH8Tr4OMQWiFoPjLfkn0W6ZRA72uZR3SkmWkBAnuchnjjH96clSnqmKkPgCyAcsGXEjEh/AAc4DveRM5fghcX2YuRl4agDPbVCCcfZDfTWaaR14GLDlzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
