travis:
  secure:
    BINSTAR_TOKEN: HZL4IEjL4fG63YBtXl56hZG361bkqxmrkH63cHfW5ZORl/MDbSGlAoVcntrvCAwK1fM05wqtFrGtCQg9ouGgkMS8GgkUuezQocTJ1ChVddt/EruQ/iMzulrAE0WJCmvrkdQnpCKZ7nt5mvhj3V/WCDhcB9HemOgEoaQYlL+71Zg+eLLR2G6mfcA9e3LRcj1hji4hYryTFtW/Erv8Ue3b534ZcVFX6jNIEEo9jB0ASiBJ4QIixH7Qg9SJLrXAAea5rC/RI3XiupLwBwmz2USd4GOL56qvbly9t/N3uNV/ZBbJshesoBXyoptOydRtlysnX2qRa6TLd9NxRw8eLgp0onu+O8CeuhIyUqmS99IfWAowpj3PjIaWscbfGOGVonlMEMP+94CvU3a5j3R0LgAJWQo4ev85S+FTd4xBhiG1AI9289uigeE2nM+TlYUI+dU4vUxtlk7KloygU5h1jJs2H4RJMql5713/t3A2gu4CSkXyWCYqHJ2JJUWkZ6wp08Tnl1+8m54jpX8nT2nLuy4uzae4eK6l0JLnsls1osvGxy5XCI4eA6IC/7SkRkctj7TGMCBf9ceACty/GqTLtySkzv5wBQK7OxrQ2Uqef4VgQgx5tghgEszUFhf7Pqc59Z8auY7ipP8x9WaLH581FNC/7853brFE12KLoiwpzGrnL4g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
