travis:
  secure:
    BINSTAR_TOKEN: bqdZ1rMnBEcWg3zoipdROiEDc3+jQHUpiV4m4W137ViirlrFVFUu/3um5jYBeJbsm4CwwWTmmgldCjOYX6iqM5HjPtgyG2C1pSZTo0xg17DDdKOvybSzfSKRAIaIXsj/Jt6z9uejos6PPb3xthf7YH0yaKnODYdYQOHpOxBQ9yEuprmjEjWaupxB74EMeUuyv9GS4m8Zznvjhf0RYoFhL7pxlM8gY0RR32L6eQUN/47RY5EATGvzpyNzP/j95oluUAb3lGoReSDxptOyWGfFJyh3K+uFZxt2df5USZAF61/Oe4ntDzTy/bN5OdqSpBjHDoIMf84JpmyfIlxvaOnZt3Vnzh3f5UB9HZSLSeo7z+M8Eu/yiZYxXdVLOo83CRbGRDr3Vj4134O0FsqRdB7f8fvt2I4yLLzhk2H8wTzKK+X7nDTErF9Luh97d5m9AbPPp1mosKQsdZ4BWQcE7QEinbl58UaOTsOCRiDvXJrQZObap4xwE8hwbIK6UXi6YwLBmuBufIfFILIKLs0fgY2hKMTJkCaxqsXrWQ2onhvid5XuXzP/GGtqBRBk57ZJ7wsUTx6g8KOKcnmf/+xssgcVZRDFxm9Rtx47XuY9ePf0uGyOKUeu6rI46p9qIO3b8YSmCdFrTe11mJFpWvgIKKMRa0Xhn7C6BxA1uN7yhgFatLk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
